baseURL = "https://nbasastro.org"
languageCode = "en-us"
title = "Northern Berkshire Astronomical Society"
theme = "ananke"
canonifyURLs = false

[params]
  custom_css = ["css/custom.css"]
  logo = "/images/logo-transparent.png"
  mainSections = ["posts", "articles", "gallery"]

[markup.goldmark.renderer]
  unsafe = true
