baseURL = "https://nbasastro.org"
languageCode = "en-us"
title = "Northern Berkshire Astronomical Society"

[params]
  subtitle = "Clear Skies over the Berkshires"
  banner = "images/m31_banner.jpg"
  logo = "images/nbas-grey.png"
  site_version = "v1.1.2"

[frontmatter]
  date = ["lastmod", "date", "publishDate"]

[pagination]
  pagerSize = 20

[taxonomies]
  author = "authors"
  tag = "tags"
  series = "series"
  constellation = "constellations"
  knowledgetopics = "knowledgetopics"


  # STARS
  stars_variable = "stars_variable"
  stars_nearby   = "stars_nearby"
  stars_bright   = "stars_bright"
  stars_multiple = "stars_multiple"
  stars_exotic   = "stars_exotic"
  stars_exoplanet= "stars_exoplanet"

  # SSO (Solar System Objects)
  sso_planets   = "sso_planets"
  sso_meteors   = "sso_meteors"
  sso_comets    = "sso_comets"
  sso_asteroids = "sso_asteroids"

  # DSO (Deep Sky Objects)
  dso_messier  = "dso_messier"
  dso_caldwell = "dso_caldwell"
  dso_ngc      = "dso_ngc"
  dso_other    = "dso_other"

[permalinks]
  articles = "/articles/:year/:month/:title/"
  guides = "/guides/:sections[1:]/:contentbasename/"
  pages = "/:contentbasename/"

[related]
  threshold = 1
  includeNewer = true
  toLower = true

  [[related.indices]]
    name = "series"
    weight = 100  # A shared series is a perfect match

  [[related.indices]]
    name = "tags"
    weight = 100   # Shared tags are a strong match

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[cascade]]
  [cascade.target]
    path = "{/dso_messier/**,/dso_caldwell/**,/dso_ngc/**,/dso_other/**,/sso_planets/**,/sso_comets/**,/sso_asteroids/**,/sso_meteors/**,/stars_bright/**,/stars_nearby/**,/stars_variable/**,/stars_multiple/**,/stars_exotic/**,/stars_exoplanet/**}"
  [cascade.layout]
    layout = "astro-explorer"
